CREATE A JAVA PROGRAM THAT WILL ALLOW THE USER TO KEEP ON ACCEPTING ANY NUMBERS (INTEGER OR DOUBLE),
THE PROGRAM WILL ONLY STOP ACCEPTING INPUTS IF THE USER HAS ALREADY ENTERED ANY NEGATIVE NUMBER OR THE
NUMBER ZERO WAS INPUTTED (THE LAST INPUT IS NOT INCLUDED IN THE COMPUTATION).
COMPUTE AND DISPLAY THE SUM OF:
	ALL WHOLE NUMBERS DIVISIBLE BY 2,
	ALL WHOLE NUMBERS DIVISIBLE BY 3,
	ALL WHOLE NUMBERS DIVISIBLE BY 5

NOTE:
	IF THE USER ENTERS A NUMBER THAT HAS A FRACTIONAL PART (REGARDLESS POSITIVE OR NEGATIVE),
	DO NOT INCLUDE IN THE COMPUTATION.
	YOU CAN USE ANY LOOPING STRUCTURE.
NAME THE FILE: DetermineNumbers.java


--------------------------------------------
SAMPLE RUNNING PROGRAM:

ENTER NO.:  2
ENTER NO.:  2.5
ENTER NO.:  25
ENTER NO.:  32
ENTER NO.:  100
ENTER NO.:  16
ENTER NO.:  15
ENTER NO.:  8
ENTER NO.:  1000
ENTER NO.:  0.0000      -> STOPS THE INPUT

SUM OF ALL WHOLE NUMBERS DIVISIBLE BY 2 = 1173
SUM OF ALL WHOLE NUMBERS DIVISIBLE BY 3 = 15
SUM OF ALL WHOLE NUMBERS DIVISIBLE BY 5	= 1140
<--- end of program --->

--------------------------------------------
SAMPLE RUNNING PROGRAM:

ENTER NO.:  50
ENTER NO.:  75
ENTER NO.:  12
ENTER NO.:  2.3333
ENTER NO.:  0.3333
ENTER NO.:  55
ENTER NO.:  -2      -> STOPS THE INPUT

SUM OF ALL WHOLE NUMBERS DIVISIBLE BY 2 = 62
SUM OF ALL WHOLE NUMBERS DIVISIBLE BY 3 = 87
SUM OF ALL WHOLE NUMBERS DIVISIBLE BY 5	= 180
<--- end of program --->
