CREATE A JAVA PROGRAM THAT WILL ALLOW THE USER TO KEEP ON ACCEPTING ANY NUMBERS (INTEGER OR DOUBLE),
THE PROGRAM WILL ONLY STOP ACCEPTING INPUTS IF THE USER HAS ALREADY ENTERED ANY NUMBER MORE
THAN 1000 OR THE NUMBER ZERO WAS INPUTTED (THE LAST INPUT IS NOT INCLUDED IN THE COMPUTATION).
COMPUTE AND DISPLAY THE SUM OF:
	ALL NEGATIVE WHOLE NUMBERS,
	ALL POSITIVE WHOLE NUMBERS,
	ALL NEGATIVE NUMBERS WITH FRACTIONAL PART, AND
	ALL POSITIVE NUMBERS WITH FRACTIONAL PART

NOTE: YOU CAN USE ANY LOOPING STRUCTURE
NAME THE FILE: DetermineNumbers.java


--------------------------------------------
SAMPLE RUNNING PROGRAM:

ENTER NO.:  1.2
ENTER NO.:  -12.0
ENTER NO.:  -5.1
ENTER NO.:  3.0
ENTER NO.:  -1.5
ENTER NO.:  2.1
ENTER NO.:  5.0
ENTER NO.:  12.00003
ENTER NO.:  00.001
ENTER NO.:  0.0000      -> STOPS THE INPUT

SUM OF ALL NEGATIVE WHOLE NUMBERS             = -12
SUM OF ALL POSITIVE WHOLE NUMBERS             =   8
SUM OF NEGATIVE NUMBERS WITH FRACTIONAL PART  =  -6.6
SUM OF POSITIVE NUMBERS WITH FRACTIONAL PART  =  15.30103
<--- end of program --->

--------------------------------------------
SAMPLE RUNNING PROGRAM:

ENTER NO.:  5.2
ENTER NO.:  -12.333
ENTER NO.:  -005.21
ENTER NO.:  1.0
ENTER NO.:  -7.50
ENTER NO.:  1001      -> STOPS THE INPUT

SUM OF ALL NEGATIVE WHOLE NUMBERS             = 0
SUM OF ALL POSITIVE WHOLE NUMBERS             = 1
SUM OF NEGATIVE NUMBERS WITH FRACTIONAL PART  =  -25.043
SUM OF POSITIVE NUMBERS WITH FRACTIONAL PART  =  5.2
<--- end of program --->
